### ISSUE TITLE
Run worker

### ISSUE THREAD

**Issue by dachirui** [OpenMined/pygrid-admin#101]
## Question
How can I run/connect a worker with the domain and see the worker on http://localhost:3000/infrastructure (worker tab)?

**Comment by victorperezc** [comment]
Hi @dachirui ! Thanks for your question. I suggest you take a look at the latest Jupiter notebooks on how to run computations on remote workers, and launch them on a cloud provider [here](https://github.com/OpenMined/PySyft/blob/pygrid_demo/examples/pygrid/tutorials/%5BData%20Scientist%5D%20PyGrid%20Remote%20Inference.ipynb). Regarding the infrastructure tab, I believe this is broken rn and we're working to get it fixed asap.

**Comment by dachirui** [comment]
Thank you very much! It works until I try to create a dataset on the owner side provided [here](https://github.com/OpenMined/PySyft/blob/pygrid_demo/examples/pygrid/tutorials/%5BData%20Owner%5D%20PyGrid%20Remote%20Inference.ipynb) 
When I run `dataset = domain.datasets.create('diabetes-dataset.tar.gz')
` it throws 
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-06e26cbf9621> in <module>
----> 1 dataset = domain.datasets.create('diabetes-dataset.tar.gz')
      2 dataset.pandas

AttributeError: 'GridClient' object has no attribute 'datasets'`

Is there any other attribute to create a dataset?

Thanks

**Comment by victorperezc** [comment]
@dachirui The code that implements those methods only lives inside the `pygrid_demo` branch. You will have to reinstall PySyft from that branch `pip3 install git+https://github.com/OpenMined/PySyft.git@pygrid_demo` so those methods are accessible.

**Comment by dachirui** [comment]
@victorperezc thank you very much, was ok until dataset creation where same line throws `JSONDecodeError: Expecting value: line 1 column 1 (char 0)`
I am looking for it but it could be a problem related with Python version. I am using 3.8.

**Comment by victorperezc** [comment]
Yeah this can happen because of a variety of things. The endpoint that accepts datasets is very sensible and only accepts specific formats. For instance, try to make sure that your dataset follows this
* It's a compressed directory with extension .gz.zip
* The compressed directory contains .csv files and a manifest, tags and description files.
* Make sure the csv files are comma separated

Since this matter is out of the scope of this repository I suggest you either open an Issue in PyGrid or send me a message over Slack. I will be happy to help.

**Comment by victorperezc** [comment]
Closing the Issue now ~
